### ISSUE TITLE
bump to latest CodeNarc version (1.3)

### ISSUE THREAD

**Issue by davehenton** [cinch-financial/codeclimate-codenarc#5]
@jisikoff Hey there, Dave here with Code Climate Support. Would it be possible for you to bump this engine to incorporate the newest CodeNarc release ([version 1.3](https://github.com/CodeNarc/CodeNarc/releases/tag/v1.3))?

Let me know if you have any questions, or if there's anything I can do for you on my end. Thanks!

**Comment by blatyo** [comment]
No developers work for cinch anymore. Your best bet is to fork.

**Comment by jisikoff** [comment]
I forked it previously to https://github.com/jisikoff/codeclimate-codenarc  I will try to update it in the next week or two.

**Comment by jisikoff** [comment]
PR on my fork https://github.com/jisikoff/codeclimate-codenarc/pull/1/files

**Comment by jisikoff** [comment]
Merged to master at https://github.com/jisikoff/codeclimate-codenarc

**Comment by davehenton** [comment]
Hey @jisikoff -- just letting you know that we moved over to your fork now (https://github.com/jisikoff/codeclimate-codenarc) since https://github.com/cinch-financial/codeclimate-codenarc is no longer maintained. Thanks for the help!

**Comment by davehenton** [comment]
Closing this, as Code Climate's plugin now runs off https://github.com/jisikoff/codeclimate-codenarc
